name: 编译 VST3

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 初始化子模块
        run: |
          git submodule init
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: 配置
        run: cmake -B build -A x64

      - name: 编译
        run: cmake --build build --config Release --parallel

      - name: 上传插件
        uses: actions/upload-artifact@v4
        with:
          name: AutoVocalMatch-Windows
          path: |
            build/AutoVocalMatch_artefacts/Release/VST3/AutoVocalMatch.vst3
